name: Dev Build and Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build Package
        id: build_package
        run: ./build.sh --dev --download-deps

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(make print-version BUILD_TYPE=dev)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Create Dev Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: ${{ steps.get_version.outputs.version }}
          prerelease: true
          body: |
            **Notice:** This is an automated development build. It may not be fully tested.

            **Bundled Binaries:**
            This build integrates the following external dependency versions:
            - [itsPLK/ps5-elfldr](https://github.com/itsPLK/ps5-elfldr): [${{ steps.build_package.outputs.elfldr_ver }}](https://github.com/itsPLK/ps5-elfldr/releases/tag/${{ steps.build_package.outputs.elfldr_ver }})
            - [itsPLK/ps5-kexp](https://github.com/itsPLK/ps5-kexp): [${{ steps.build_package.outputs.kexp_ver }}](https://github.com/itsPLK/ps5-kexp/releases/tag/${{ steps.build_package.outputs.kexp_ver }})
            - [itsPLK/ps5-payload-manager](https://github.com/itsPLK/ps5-payload-manager): [${{ steps.build_package.outputs.pldmgr_ver }}](https://github.com/itsPLK/ps5-payload-manager/releases/tag/${{ steps.build_package.outputs.pldmgr_ver }})
          files: 'y2jb_update.zip'
